SUPABASE_URL = "https://lhvjuqiedqmunnhpjwpu.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxodmp1cWllZHFtdW5uaHBqd3B1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDcyMjQ4MCwiZXhwIjoyMDYwMjk4NDgwfQ.uQHbbFrFNmBuh-xUg2bq1OyFHGwY7olK9ui8l8d5Y3c"
